### ISSUE TITLE
If and floating point 

### ISSUE THREAD

**Issue by wolfv** [pybee/batavia#12]
```
if 2.1 > 3.123:
    print("a")
else:
    print("b")
```
--> b

but

```
if 2 > 3.123:
    print("a")
else:
    print("b")
```
--> a

Seems like an error in the comparison.

**Comment by freakboy3742** [comment]
Confirmed - thanks for the report!

It looks like it's hitting the right comparison operator; it's the arguments that aren't being handled correctly. More investigation is required.

**Comment by wolfv** [comment]
Seems to be fixed!
