### ISSUE TITLE
Create better styles for Batavia demo page

### ISSUE THREAD

**Issue by JasonThomasData** [pybee/batavia#218]
We can add some styles in the same style as the Batavia docs page, here: http://pybee.org/contributing/what/

We can add some font styles and other pretty changes to give a better first impression.

**Comment by glasnt** [comment]
The basic solution here would be to reformat the page with something as simple as getskeleton, use the pybee.org font (Cutive) and just make it look a little bit nicer to look at in general. 

As noted during the sprints, none of the JS can change as there's a lot of moving parts to get the page to work. The functionality can be tested by making sure the actual functionality of the page (write python, execute in browser) still works.

**Comment by JasonThomasData** [comment]
Cool, good I agree... wasn't suggesting we change any JS actually, it's a simple CSS thing
