### ISSUE TITLE
Syntax highlighting on Batavia's initial demo page

### ISSUE THREAD

**Issue by JasonThomasData** [pybee/batavia#219]
There are JavaScript plugins that give text boxes syntax highlighting.
Great for code readability, highlighting keywords, functions and different types.

**Comment by JasonThomasData** [comment]
Here's some examples for what I'm talking about, but not necessarily in the style we want.

http://alexgorbatchev.com/SyntaxHighlighter/manual/themes/django.html
https://highlightjs.org/

**Comment by glasnt** [comment]
I think this a good idea, but the only problem here is that I'm not sure there's a decent solution to have live syntax highlighting on an editable textarea. 

If there is, by all means.

**Comment by JasonThomasData** [comment]
Here is a better example @glasnt 
http://codemirror.net/
