### ISSUE TITLE
Longs not supported

### ISSUE THREAD

**Issue by swenson** [pybee/batavia#223]
Entering a number that is larger than a double can support seems to cause a type error.

e.g., `2**64` gives:

```
TypeError: undefined is not a constructor (evaluating 'batavia.modules.marshal.r_PyLong(vm,p)')
```

Rough TODOs:
- [x] Marshal PyLongs 
- [x] Auto-promote arithmetic (2**1024)
- [x] Auto-demote float arithmetic (2**1024/3)
- [x] Make sure all arithmetic operations and builtins are ported over correctly

**Comment by glasnt** [comment]
Given #251, running `2**64` on the testbed now doesn't break. Is this one now resolved, @swenson?

**Comment by swenson** [comment]
Yep! This should be done now.

**Comment by glasnt** [comment]
Heck yeah! ✨🎉✨
