### ISSUE TITLE
Why not add option to transpile python to js instead of a VM

### ISSUE THREAD

**Issue by sideffect0** [pybee/batavia#239]
* compile python to js
* use google closure compile to minimise it
* implement python3.5 features including async/await  
I think that will be the betterway for perf & reducing the complexity, we can also add plugins for the system, been looking for a python solution in web, checked many but all have problems; believe me am also worked on web frontend technologies, if we are going to focus more on VM implementation of python like `brython`, it will not be effective to the pythonistas who are trying to do `python` in browser

**Comment by funkybob** [comment]
Because then we wouldn't be able to export bytecode from a server-side Python to run on the browser...

**Comment by sideffect0** [comment]
@funkybob why one need bytecode ? it again slows down the browser performance,
like C > CPython

**Comment by glasnt** [comment]
Hi @sideffect0, the reasons behind why this design was chosen are described at a high level in this talk by @freakboy3742

http://pyvideo.org/djangocon-europe-2016/beyond-web-20-django-and-python-in-the-modern-web-ecosystem.html

**Comment by sideffect0** [comment]
@glasnt okey :)

**Comment by glasnt** [comment]
@sideffect0 batavia covers python to JavaScript. For Android, you're after the VOC project. 

Please have a look over http://pybee.org. If the reasoning behind the overall design choices is still unclear, please don't hesitate to ask questions.

**Comment by sideffect0** [comment]
@glasnt what all these projects missing is a good documentation, even `voc` :(

**Comment by glasnt** [comment]
@sideffect0 Oh? The project page should have a [basic overview](http://pybee.org/project/projects/bridges/voc/) and links to [more detailed documentation](https://voc.readthedocs.io/). 

You're more than welcome to help out improving the documentation, all contributions are welcome :)

**Comment by freakboy3742** [comment]
@sideffect0 It sounds like there is some sort of disconnect between what you think Batavia is, and what you're trying to do. It's entirely possible that Batavia may not be the right project for your needs. Batavia isn't a transpiler, and we have no plans to "add one" - because transpilation is a completely different approach to what we're trying to do.

You've mentioned Javascript and Android, Transpilation, virtualdom... what exactly are *you* trying to do? If you can provide details, we might be able to clarify where the problem lies.

**Comment by sideffect0** [comment]
@freakboy3742 was discussing about, not just `batavia` or `voc`, my doubts are
* any way i can add features to  batavia VM from javascript land updates
* its about voc https://github.com/pybee/voc/issues/245
* async, with like language pattern implementation in VM ( any near plans )
* a good documentation for voc ( android ) & batavia users

**Comment by freakboy3742** [comment]
@sideffect0 Ok - so first off: both Batavia and VOC are very young projects. As a result, there are things that aren't implemented. Async is one; with statements are another. Over time, I'd expect these to be implemented, but as this is a all volunteer work, I can't really make any guarantees on when they will be implemented. If you happen to know any sources of funding for FOSS development, I'd love to hear about them.

We have *some* documentation, but there's always room for improvement. However, the "end user" documentation will always be fairly simple for these projects - take your Python code, and run it. It isn't clear to me what *specific* documentation you think is missing.

As for your first point - I'm not sure what you're asking. This is an open source project, so you're free to contribute. If you're asking whether the Python runtime can interact with the Javascript runtime - the answer is yes, and if you take a look at the sandbox, you'll see examples of that (opening windows, setting page titles, etc). If you mean something else... you'll need to ask a more specific question.

**Comment by sideffect0** [comment]
@freakboy3742 am happy to contribute :+1:
