### ISSUE TITLE
unexpected results for list // complex

### ISSUE THREAD

**Issue by jstoebel** [pybee/batavia#254]
Implementing list // complex() Python throws `TypeError: unsupported operand type(s) for //: 'list' and 'complex'` but expectation from the unit test is `<class 'TypeError'> : can't take floor of complex number.`

Is this a bug or am I misunderstanding something? I'd love to work on this if its not to...complex \*rim shot\*

**Comment by freakboy3742** [comment]
Which test are you referring to? I'm not seeing any explicit tests in the complex data type; and the auto generated tests seem to be working as advertised:

```
In [1]: x = [1,2,3]

In [2]: y = 1+2j

In [3]: x//y
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-ed06ee651b37> in <module>()
----> 1 x//y

TypeError: can't take floor of complex number.
```

Can you provide the example where you're getting the "unsupported operand" error?

**Comment by jstoebel** [comment]
Apologies, I didn't have my virtualenv activated before. Those results were for Python2 and thus invalid. When I run your example in Python3.4 I get the same results.
