### ISSUE TITLE
Dictionary, set, and frozenset implementations have duplicate key problems

### ISSUE THREAD

**Issue by swenson** [pybee/batavia#274]
Since JavaScript is pretty lax about equality, we get unexpected behavior when mixing types in dictionaries and sets:

```
d = {}
d['1'] = 123
d[1] = 456
print(d)
```

gives `{'1': 456}` for example, and

```
print(set([1, '1']))
```

gives `{'1'}`.

I think we may have to roll our own hash table implementation to fix this.

**Comment by rkrp** [comment]
I would like to work on this one 😄 

I have forked and cloned the source. Trying out Batavia locally. I am going through the documentation right now. Please let me know how to proceed further.

**Comment by swenson** [comment]
Oh, sorry @rkrp -- I think I merged the fix for this the other day and forgot to close this issue! :( https://github.com/pybee/batavia/pull/288

**Comment by swenson** [comment]
There are lots of other things to work on. I recommend checking out https://github.com/pybee/batavia/issues/47 and https://github.com/pybee/batavia/issues/46 for example.

**Comment by rkrp** [comment]
@swenson  Oh. That's okay. 

But, #47 and #46 has a `first-timers-only` tag. I have sent a handful of PRs to other projects (mostly small stuff) which has been accepted and merged. So, I am technically not a first timer. Would it be okay for me to be working on these issues?

**Comment by swenson** [comment]
Yes. I think first-timers-only is meant for first-timers-only to this project, as they are meant to gently introduce you to the codebase :)
On Oct 15, 2016 03:55, Krishna Ram Prakash R <notifications@github.com> wrote:@swenson  Oh. That's okay. 

But, #47 and #46 has a first-timers-only tag. I have sent a handful of PRs to other projects (mostly small stuff) which has been accepted and merged. So, I am technically not a first timer. Would it be okay for me to be working on these issues?
