### ISSUE TITLE
Possible bug/possible me? Errors running tests

### ISSUE THREAD

**Issue by williln** [pybee/batavia#290]
Hi @freakboy3742 @glasnt @phildini: 

I ran the tests last night after doing all the things in the Getting Started, and 21 tests failed, mostly in tests.modules.test_math.MathTests. I scrolled through the tests that failed and it seems the tests are failing with these errors: 

-  'AttributeError'> : 'module' object has no attribute 'isclose'
- 'AttributeError'> : 'module' object has no attribute 'gcd'
- <class 'TypeError'> : 'float' object cannot be interpreted as an integer
- AttributeError: 'module' object has no attribute 'inf' 

Sample screenshot:

<img width="1280" alt="screen shot 2016-10-06 at 9 01 25 am" src="https://cloud.githubusercontent.com/assets/2286304/19160271/197a59a0-8ba4-11e6-8c37-44cf813e4523.png">

It seems unlikely that tests are failing only for me :) Any ideas as to what I don't have installed or need to do differently? I checked and I don't have uncommitted changes from DjangoCon Europe, and my fork is in sync with the main branch.

**Comment by phildini** [comment]
It's almost certainly not you, even if the error is only occurring for you. If you followed the docs and are getting an error, we need to fix the docs!

I don't know the exact cause, here, and Katie/Russell won't be on for a bit. @swenson may have come across this before.

Can you tell us a bit more about where you're running this? Mac/Linux/Windows, etc?

**Comment by williln** [comment]
I'm running on a Mac OS X El Capitan v. 10.11.16. I had to do a couple things last night to get properly set up. (I don't use a lot of modern tools for my day job, so things like homebrew are still new to me!) 

- The instructions I was following are [here](http://batavia.readthedocs.io/en/latest/internals/contributing.html#setting-up-your-development-environment)
- homebrew wasn't working, which turned out to be a problem with El Capitan and permissions and such. Following instructions [here](http://stackoverflow.com/questions/24652996/homebrew-not-working-on-osx) fixed that issue, and then I was able to install phantomjs. 
- I don't think there was anything else weird?

**Comment by swenson** [comment]
Hi @williln.

It sounds like the `math` module isn't being loaded.

When I run this test locally (and on CircleCI), it seems to be okay:

```
python setup.py test -s tests.modules.test_math.MathTests.test_math_isclose_int_int
```

I suspect that if you were updating an old copy of batavia, something might have gotten lost. I'd check the following things:

* In `Makefile`, check that there is a line under `BASE_FILES` that says `    batavia/modules/math.js \` -- this ensures that the `math.js` file is loaded, which contains the math module
* Check that `batavia/modules/math.js` exists, and that there is a line that says `    isclose: function(args, kwargs) {` to define that function.
* Maybe try deleting `batavia-all.js`, `batavia-all.min.js`, `batavia.js`, and `batavia.min.js` from the repo directory and running `make` to rebuild it
* Check that there is an `isclose` function defined in `batavia-all.min.js`, for instance, by doing `grep -e isclose batavia-all.min.js`.

**Comment by glasnt** [comment]
Hi @williln, 

I'm also on El Cap, so yay similar dev environments :)

One of the major changes to batavia recently is the requirement for `ouroboros`. I didn't have this locally, but when I tried to run `make`, I got the error `'ouroboros' folder must be present here or in the parent directory to compile stdlib`, which was informative.

If you already have ouroboros setup, then that's great :)

But if you're still having errors, what I suggest: clone a copy of the canonical master code (as opposed to your fork) which we know works in CircleCI, activate your virtual environment, and try the test again: 

```shell
git clone git@github.com:pybee/batavia batavia_master
cd batavia_master
make
python setup.py test -s tests.modules.test_math.MathTests.test_math_isclose_int_int
```

Let us know if you have any more problems.

**Comment by williln** [comment]
@swenson I followed all your instructions and got these results: 

> In Makefile, check that there is a line under ```BASE_FILES``` that says ```batavia/modules/math.js \``` -- this ensures that the ```math.js``` file is loaded, which contains the math module

That line was there 

> Check that ```batavia/modules/math.js``` exists, and that there is a line that says ```isclose: function(args, kwargs) {``` to define that function.

That module was there, and contained that line 

> Maybe try deleting ```batavia-all.js```, ```batavia-all.min.js```, ```batavia.js```, and ```batavia.min.js``` from the repo directory and running ```make``` to rebuild it

Did this, and it seemed to go okay? Not sure what was supposed to happen, but this is what happened: 
<img width="632" alt="screen shot 2016-10-07 at 9 01 35 am" src="https://cloud.githubusercontent.com/assets/2286304/19197033/b37014be-8c6c-11e6-96ae-120086c19710.png">

> Check that there is an ```isclose``` function defined in ```batavia-all.min.js```, for instance, by doing ```grep -e isclose batavia-all.min.js```.

Ran the grep command, and got something that looked really messy? Can someone let me know if this indicates a problem? 
<img width="1279" alt="screen shot 2016-10-07 at 9 02 47 am" src="https://cloud.githubusercontent.com/assets/2286304/19197073/dbb076ee-8c6c-11e6-80ca-63891602d964.png">

@glasnt I'll try your tips once I hear back on whether following @swenson's instructions resulted in an error, or just a lot of information in the console :)

**Comment by swenson** [comment]
@williln That all looks correct. :/ Not sure why it's not working for you. I'd try @glasnt's tips next.

**Comment by williln** [comment]
@glasnt Still having problems. I deleted my fork entirely and re-cloned, following the instructions [here](http://batavia.readthedocs.io/en/latest/internals/contributing.html#setting-up-your-development-environment) to the letter, except that the ```git clone git@github.com:<your github username>/batavia.git``` command didn't work. I could clone using the URL from the web interface, which for me is ```https://github.com/williln/batavia.git```. I don't know if that matters? 

I ran just  ```python setup.py test -s tests.modules.test_math.MathTests.test_math_isclose_int_int``` and the test failed :( So I am still having an issue. The failure is: 

```
test_math_isclose_int_int (tests.modules.test_math.MathTests) ... FAIL

======================================================================
FAIL: test_math_isclose_int_int (tests.modules.test_math.MathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/laceywilliamshenschel/git/batavia-dev/batavia/tests/utils.py", line 1302, in func
    substitutions=SAMPLE_SUBSTITUTIONS
  File "/Users/laceywilliamshenschel/git/batavia-dev/batavia/tests/utils.py", line 1376, in assertTwoArgModuleFuction
    substitutions=substitutions)
  File "/Users/laceywilliamshenschel/git/batavia-dev/batavia/tests/utils.py", line 504, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: ">>> [65 chars] y)\nTrue\n\n>>> import math\n>>> f = math.isc[78149 chars]\n\n" != ">>> [65 chars] y)\n<class 'AttributeError'> : 'module' objec[102088 chars]\n\n" : Global context: Error running math module test_math_isclose_int_int

----------------------------------------------------------------------
Ran 1 test in 1.949s

FAILED (failures=1)
```

**Comment by williln** [comment]
This feels like such a silly thing; the tests work fine in the master repo, I cloned that repo, the tests should run. I have ```ouroboros``` set up. I feel like this: 
![2436074097_1b6296344b](https://cloud.githubusercontent.com/assets/2286304/19255208/435946e0-8f10-11e6-8faa-e60d6f861631.jpg)

**Comment by swenson** [comment]
Okay. This was super confusing to me, so I checked the docs, and I was enlightened:

![image](https://cloud.githubusercontent.com/assets/33404/19255815/65d1b31e-8f16-11e6-97f0-2d14a2ffcd06.png)

This is CPython having an error, not us! We run the tests on CPython 3.5, but they currently fail for 3.4 because the math library added new functions in 3.5 (like `isclose`).

I think it's best if we just comment out the tests that only work in 3.5. This is totally my bad.

**Comment by glasnt** [comment]
I had a live-chat with @williln and we worked out a few things: 

The `git clone git@` invocation wasn't working because she doesn't have SSH keys setup for GitHub. 

The tests weren't working because of the 3.5.1 issue. She had 3.4.1 system locally, we setup `pyenv` with 3.4.4, got the same math test error, setup 3.5.1, and that specific math test worked. 

I'm going to put together a PR to ensure that we're specifying 3.4.4 as per the README (for now) in the tutorial, and also recommend the use of pyenv.

**Comment by swenson** [comment]
👍 @glasnt -- thanks!

**Comment by freakboy3742** [comment]
We don't have to comment out the tests; we can make them a conditional test with the `skipIf` or `skipUnless` decorators:
```
import sys
from unittest import skipUnless, TestCase

class MyTestCase(TestCase):
    @skipUnless(sys.version() >= (3,5), "feature introduced in Python 3.5")
    def test_isclose(self):
        ....
```

As for docs recommending `pyenv` - sounds good to me. pyenv is the "official" replacement for virtualenv; they're not identical, but they're close, and virtualenv comes packaged out of the box with Python 3.5.

Unless, of course, you're using ubuntu, because they borked it good.

**Comment by freakboy3742** [comment]
/me facepalms - you said pyenv, not pyvenv. Ignore me :-)

**Comment by williln** [comment]
I finished running the tests last night and they all pass! Thank you @glasnt and @swenson for your help! I'm closing this issue now :)
