### ISSUE TITLE
hex() produces incorrect output

### ISSUE THREAD

**Issue by rkrp** [pybee/batavia#305]
`hex()` produces incorrect output. 
```
>>> print(hex(3735928559))
0x3735928559
```
instead of giving `0xdeadbeef`

This is because, hex conversion is done by `toString()` method and `toString()` method is overridden [here](https://github.com/pybee/batavia/blob/e11f49e6423b3a30dc7b51d9120d961e45554c82/batavia/types/Int.js#L36) in `Int.js`

So, the implementation of `hex()` in `builtins.js` will always return 

    return this.val.toFixed(0);

which is of course, not the hexadecimal value of the integer. 

Would like to hear your thoughts on this, before I can work on a PR 😄

**Comment by glasnt** [comment]
Resolved in https://github.com/pybee/batavia/pull/316 🎉
