### ISSUE TITLE
`set` iterator yields floats as strings, or possible ordering issue

### ISSUE THREAD

**Issue by candeira** [pybee/batavia#332]
My `bytes` implementation was initialising objects from `set` fixtures perfectly, and then I rebased on master and these errors happened:

```
  >>> f = bytes
  >>> x = {1, 2.3456, "another"}
  >>> f(x)
- <class 'TypeError'> : 'float' object cannot be interpreted as an integer
?                        ^^^^
+ <class 'TypeError'> : 'str' object cannot be interpreted as an integer
?                        ^ +
```

Since the `bytes()` initialisation works fine when iterating over dicts, lists and tuples, I suspect the reworking of `set` objects on top of the new `dict`s here: https://github.com/pybee/batavia/pull/288, or maybe some ordering/substitutions issue.

@swenson: if you don't mind, I'd like to dib this one, and learn more about the dict/set implementation. I looked at the commit yesterday, and was intrigued.

**Comment by swenson** [comment]
This looks like an ordering issue. CPython randomizes the order of sets every time, so we shouldn't write tests that rely on the order.

**Comment by candeira** [comment]
So it can be fixed using substitutions? Most of the operations for failing tests depend on getting the right exceptions on the right order.

**Comment by candeira** [comment]
I've worked around this issue in commit c3dd12c8a11331ddd437226fedf7cccbf5e4b66d
