### ISSUE TITLE
Restructure the doc library

### ISSUE THREAD

**Issue by thatdocslady** [pybee/batavia#346]
Currently in the RTD doc set, there are a few improvements that can be done to the TOC structure and order of topics. Some examples:

- The FAQ and Getting Started are nested inside "About Batavia" and collapsed by default.
- The "About Batavia" section should contain community/development information and moved to the end of the TOC.
- How-to guides doesn't actually contain info on how to use the software but instead contains contributing/docs info.
- Generally, the breakdown of topics between intro/topic/reference can be improved.

I'm waiting to tackle this until PR #341 is resolved because it touches some of the main content files and here be conflicts.

**Comment by freakboy3742** [comment]
Fixed in 26d6833.
