### ISSUE TITLE
Some builtins should raise `TypeError: foo() takes no keyword arguments`

### ISSUE THREAD

**Issue by carljm** [pybee/batavia#367]
A number of builtin methods implemented in C in CPython can never take keyword arguments; examples include `tuple.count()` and `tuple.index`. If you try to pass any keyword argument, you'll get `TypeError: xxx() takes no keyword arguments`. This should be reproduced in batavia.

**Comment by LMVogel** [comment]
Is this still open? Or should it be closed, based on commit 

`67514d77b7d1dacdbe8a12f622ff2c310fb8d629?`

**Comment by freakboy3742** [comment]
@LMVogel Looks like you're right - thanks!

**Comment by krtk6160** [comment]
@freakboy3742 That commit wasn't accepted, and the pull request was never merged. I'm not sure if the problem still exists, though. Since it wasn't resolved by that commit, shouldn't the issue remain open?
