### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by clach04** [pybee/batavia#375]
This may be a doc issue, it's not clear what expected the error handling is. For example the following script ran through the test server:

    addr = 99
    print(addr)

Works fine, but:

    #addr = 99
    print(addr)

fails silently. It is a runtime failure as Python is dynamic and addr does not exist at execution time.

Using a Python 2 print statement fails, at compilation time:

    #addr = 99
    print addr

And is reported clearly.

**Comment by freakboy3742** [comment]
Is it failing silently, or is it just that the exception isn't visible? If you show the javascript console, is an exception displayed?

If this is the case, you're highlighting an area where improvement is definitely called for.

**Comment by clach04** [comment]
I may be responding to this too late, there is something in the browser console if it is enabled:

    Create VM127.0.0.1:8000:259:5
    Run code...127.0.0.1:8000:261:5
    Traceback (most recent call last):
      File "C:\Users\clach04\AppData\Local\Temp\tmp48yasxky", line 2, in <module>
    NameError: name 'addr' is not definedVirtualMachine.js:821:13
    done.

Slightly off topic, with the last example (syntax error) the console shows:

    ReferenceError: customcode is not defined
    onload()
