### ISSUE TITLE
problems with user-defined classes

### ISSUE THREAD

**Issue by lucantrop** [pybee/batavia#376]
Hey, so, I was looking into how classes work, and I ran into a problem similar to #375. 
However, while
```
#foo = 'bar'
print(foo)
```
does output the correct error (inside the console),
```
Create VM
Run code...
Traceback (most recent call last):
  File "/tmp/tmp0d_dkc7o", line 2, in <module>
NameError: name 'foo' is not defined
done.
```
doing a similar thing with a user-defined class (and it's object):
```
class bar:
    pass

foo = bar()
print(foo.fail)
```
instead of reporting an `AttributeError`, simply returns `None`.
In `tests/structures/test_class.py`, there is no test for this kind of behaviour.
Also, python objects have some built-in attributes and methods that are not implemented yet (e.g. `foo.__dict__`, see `dir(foo)` for others).
I would like to work on this myself, but I could use some pointers right now.

**Comment by freakboy3742** [comment]
This has now been resolved.
