### ISSUE TITLE
Enforce code style for JavaScript files

### ISSUE THREAD

**Issue by treyhunner** [pybee/batavia#427]
I was looking at the code in `batavia/types/Tuple.js` and noticed there's a mix of tabs and spaces in that file. I went looking for a code style guide for the JavaScript files and didn't notice one (I may not have looked hard enough though).

I usually use `.editorconfig` files to dictate my indentation style for various types of files because my text editor always seems to disagree with the authors of the projects I contribute to by default.

I propose two things:
1. that batavia adopt an [EditorConfig][] file
2. that some semi-automated sed magic (or similar) be used to make the mixed indentation more consistent

Thoughts on those two suggestions?

⚠️ **Disclaimer** I'm one of the people who created EditorConfig. It is used by some pretty popular projects already though (e.g. Django, Drupal, Wordpress, Node, Angular, jQuery).

[editorconfig]: http://editorconfig.org/

**Comment by freakboy3742** [comment]
Yes to the overall goal. The intention is to enforce PEP8/eslint and other code style guides as a rebuild check, using pybee/beefore; the issue has been finding a way to deploy it. However, even in the interim, having a linting configuration defined and enforced would be desirable. If and EditorConfig definition can supplement this, all the better.

**Comment by treyhunner** [comment]
I'd say an EditorConfig definition does supplement this goal because EditorConfig is expressly meant to enforce code style within text editors automatically (avoiding linting errors before they happen) whereas ESLint catches errors after they've occur and it focuses on a larger and more specific variety of errors (because it's JavaScript-aware and JavaScript-specific).

Django, jQuery, Angular, and Node all use both EditorConfig and ESLint. The two complement each other well.
