### ISSUE TITLE
Problem while running sample.py in Batavia testbed

### ISSUE THREAD

**Issue by Sanjeev-S** [pybee/batavia#452]
**How to replicate the error**

Pull the latest branch and setup the project following the basic tutorial.
https://batavia.readthedocs.io/en/latest/intro/tutorial-0.html
https://batavia.readthedocs.io/en/latest/intro/tutorial-1.html

_Now launch localhost and run sample.py._ The console output ends with:

```
Traceback (most recent call last):
  File "sample.py", line 85, in <module>
  File "sample.py", line 79, in main
  File "sample.py", line 39, in try_builtins
TypeError: bad operand type for abs(): 'NoneType'
```

For reference:
https://drive.google.com/file/d/0B9j9MJrQhCt2STJYOVJlVHIzRmc/view?usp=sharing

**Comment by freakboy3742** [comment]
This is expected behavior; the error is thrown to check that error handling works. If you look at the code, it's the result of invoking `abs(None)`. However, I agree that it is surprising; the example should be modified so it either doesn't throw an error, or the error is caught.

**Comment by morrme** [comment]
so is the fix for the issue now just a change in the sample file?

**Comment by freakboy3742** [comment]
@morrme Correct - the sample.py file should be modified so that it catches the error and prints an appropriate response.

**Comment by morrme** [comment]
So you want to keep the abs(None) there but modify try_builtins() to catch the TypeError exception?

**Comment by freakboy3742** [comment]
Correct.

**Comment by morrme** [comment]
I looked at other code in the project to come up with a consistent error message, but it's up to you: 

```
 
def try_builtins():
    try:
        print('sum(0,1,2,3,4)', sum([0, 1, 2, 3, 4]))
        print('abs(-1)', abs(-1))
        print(bool.__doc__)
        print('min(1,2,3,4)', min([1, 2, 3, 4]))
        print('max(1,2,3,4)', max([1, 2, 3, 4]))
        print('all([True, True, False])', all([True, True, False]))
        print('any([True, True, False])', any([True, True, False]))
        print('bool("String")', bool("String"))
        print('bool(false)', bool(False))
        print('hex(14)', hex(14))
        print('oct(14)', oct(14))
        print('bin(14)', bin(14))
        print('divmod(5,2)', divmod(5, 2))
        print('pow(2, 3)', pow(2, 3))
        print('pow(2, 3, 3)', pow(2, 3, 3))

        print('abs(None)', abs(None))  # known failure (we can also edit this comment)
    
    except: Type Error:
        print "Type Error: Invalid Argument"

```

**Comment by morrme** [comment]
@freakboy3742 by the way, should my work in progress be posted here (as above) or would you prefer in an ongoing PR?

**Comment by freakboy3742** [comment]
@morrme A PR will be much more helpful.

**Comment by morrme** [comment]
@freakboy3742 OK. 

As I move this to the PR, may I ask if you have a convention for your error messages, or a suggestion for this one? I used this one based on other code in the repo.

**Comment by freakboy3742** [comment]
@morrme This is sample code. It just needs to run, and produce output that makes some sort of sense. The text of the error message doesn't actually matter that much. As long as it's understandable that it's a completely expected error, that's fine.

**Comment by Nurdok** [comment]
@freakboy3742 should this issue be closed?

**Comment by sravanthbaratam** [comment]
yes
