### ISSUE TITLE
AttributeError: 'module' object has no attribute 'utc' while running ./manage.py runserver

### ISSUE THREAD

**Issue by satyam1729** [pybee/batavia#455]
This issue was noted on starting test server on virtualenv on ubuntu 14.04.
The terminal msgt was 
in .......lib/python3.4/site-packages/django/utils/timezone.py", line 153, in <module>
    utc = pytz.utc if pytz else UTC()
AttributeError: 'module' object has no attribute 'utc'

A similar issue exists on http://stackoverflow.com/questions/26710994/django-asked-me-to-install-pytz-and-now-my-models-wont-validate-django

**Comment by satyam1729** [comment]
was solved by adding pytz to requirements.txt

**Comment by satyam1729** [comment]
have created a PR #456

**Comment by freakboy3742** [comment]
Resolved in 128996d
