### ISSUE TITLE
GSoC: Datetime and JSON modules for Batavia

### ISSUE THREAD

**Issue by ioo11** [pybee/batavia#472]
# The Project

In addition to existing modules (dis, dom, inspect, marshal, math, sys, time) I would like to write datetime and JSON. Batavia allows you to run Python code in your browser, so I think these ones will be the most useful among other modules from Python standard library that have not been implemented yet.

## JSON

Json is one of the most used data interchange format, therefore implementation of this module to Batavia is important. JavaScript is already able to work with JSON, so I have no need to rewrite CPython parser that written on C. Use the native JavaScript JSON parser will be enough.
json classes that i want to write:

- JSONDecoder
- JSONEncoder
- dumps
- loads

json.load and json.dump will not be implemented, because they have no sense without IO module.

## Datetime

Datetime is the module that supplies classes for manipulating dates and times. Module is written on Python, and I can use that implementation to rewrite it to JavaScript. In CPython datetime implementation uses modules math and time, that have already been implemented in Batavia. Datetime is a big module (), and i’m afraid that time would fail me. Therefore I want to write classes
- datetime.tzinfo
- datetime.timezone
- datetime.date
- datetime.time

during GSoC, and finish the datetime.timedelta and datetime.datetime later.

# Success Criteria

- All classes must contain the same fields and methods as CPython
- All written code must be covered by tests
- All methods must have the same behavior as CPython
- All exceptions must be handled. 

# Road-map
I try to split the work into equal parts. Each part includes implementation of one or two classes with required tests and documentations. I plan to work for 40-50 hours per week, so that amount of time will be enough.

This timeline is a rough plan and will be adjusted along the way:

0. may 4 - may 30: learn Batavia deeper, try to pass exams ahead of schedule

1. may 30 - june 25 – start working on datetime 
- 30 - 13 datetime.tzinfo (5 methods + tests)
- 14 - 25 datetime.timezone (12 methods + tests), 

2. june 26 – july 23 – finish datetime
- 26 - 9 datetime.time (22 methods + 5 properties + tests) 
- 10 - 23 datetime.date (27 methods + 3 properties + tests)

3. july 24 - august 29 – work on json
- 24 – 6 JSONEncoder, dumps
- 7 – 21 JSONDecoder, loads,
- 21 - 28 complete all unfinished things. If everything is done, it’s a good time for vacation 

# BIO

This is my first time to participate in GSoC, and Batavia is the only one project that I want work with. I have no experience in open source projects yet, and the article “First-time Contributors” was very helpful. And I would like to thank Russell Keith-Magee and Wolf Vollprecht for their advices (PR #463 ).
I have a good experience with Python (including Django), a bit less experience with JavaScript (including NodeJS). Also I know how to work with git and cricket-unittest. See more on my [github](/ioo11) .

**Comment by freakboy3742** [comment]
Hi @ioo11,

Thanks for submitting a proposal. This is a good start; here's some feedback:

* You say that datetime is implemented in Python, but the work description of suggests you're going to re-implement all the classes in Javascript. Why not use the existing implementation?

* This estimate has all the signs of someone who has worked out what they want to do, and split the work into 12 parts as an explanation for how they're going to spend 12 weeks. That doesn't lead to a very good estimate. Surely some of the methods will be difficult, and some will be easy. Which ones are which? Which ones have internal complications, and why? As a guide, 2 weeks is the *largest* granularity that would be acceptable; it's a general indication that you haven't investigated the specifics in great detail. 

* A 12 week schedule that includes a week for vacation isn't a great sign :-) But seriously, the purpose of a schedule is to tell us how you're going to use the time allocated. If you need contingency time, you're effectively advertising that *you* don't have that much confidence in your estimate, either.
 
* Your bio is more about me than it is about you :-) You don't have to fill that section in here, but when you formally submit to Google, this section needs to be more like a job application - tell us about *you*, your experience, your education, and so on. Convince us that you're the right person to get one of our GSoC slots.

**Comment by freakboy3742** [comment]
Unfortunately, this project was not accepted for GSoC 2017.
