### ISSUE TITLE
GSOC 2017: Update Batavia internals documentation, Complete implementation of float, bool, range, complex datatypes and Load a basic re module.

### ISSUE THREAD

**Issue by Sanjeev-S** [pybee/batavia#477]
# Task:

Update missing Batavia internals documentation. Complete the implementation of builtin types - float, bool, range and complex. Finally load a basic re module.

# Success:
Detailed documentation regarding all of batavia internals.
100% implementation of float, bool, range and complex.
Loading a basic regular expression library(100%) from Python 2.4 and documenting and writing tests for all extra work that needs to be done.

# Details:

## Part 1 - Improve Existing documentation (2 weeks)
Documentation of batavia internals is lacking. I scanned through the gitter conversations of the previous year since the inception of the project and collected a brain dump and some evolution of ideas. 
https://drive.google.com/open?id=0B9j9MJrQhCt2V01BWlBXSG1STXc
So in the first part of the project, propose to document batavia internals on how various parts are working together or why something is the way it is. It'll be helpful for developers new to the project to get familiar with the codebase.

## Part 2 - The data types (Completion of float, bool, range and complex) (7 weeks)

Now moving to complete the implementation of some of the built-ins. Many places, functions in relation to float are implemented but they print incorrectly. Re-implement the Python float printing function. Proceed to test and complete float operations. It is already implemented and shouldn't take much time after correcting the print function.

Complete the binary operations of bool data type - floor_divide, lshift, modulo, multiply, power, rshift, true_divide. Each of these shouldn't take more than a day on average. (I expect power to take a little longer while others like lshift and rshift can be completed on the same day). None of the inplace operations of bool are implemented(11 of them). Once the binary operations are completed, finishing this would be easy and completing all of them wouldn't take more than 2-3 days.

None of the operations of range are not implemented. In binary operations there are add, and, eq, floor_divide, ge, gt, le, lshift, lt, modulo, multiply, ne, or, power, rshift, subtract, true_divide and xor. A lot of combinations would be unsupported. But there are a lot of subtleties, like:
```
>>>range(3,10) + [1]
[3, 4, 5, 6, 7, 8, 9, 1]
>>> range(3,10) > 5
True
```
After completing the binary operations, proceed to complete all it's inplace operations.

Complex is almost completed already. 2 binary operations need to be completed multiply and power and it's inplace variants. Wrap this part, by completing it.

## Part 3 - Re module (3 weeks)
I understand that a lot of the rest of the standard library implementation depends on the re module. So it makes sense to get this part started.
https://github.com/nikhaldi/_sre.py is a pure python implementation of CPython 2.4 _sre module. 
First load it and get a basic regex support working. At this point it will require detailed analysis what are the subtle differences. Research and document with tests new features that need to be implemented in future.

# Schedule

## Community Bonding: May 4 – 30

Get involved with discussions on Gitter.
Investigate the exact inter-working of all batavia components.
Investigate how to load modules and write tests for them.

## Week 1-2: May 30 – June 2 and Jun 5 - June 9

Analyze all components of the codebase in great detail. 
Refine existing knowledge from Gitter, issues and PRs. 
Prepare a detailed documentation of batavia internals. 
Add additional documentation on using batavia.

## Week 3: June 12 – 16

Re implement the python float printing function. Complete all float operations.

## Week 4: June 19 – 23

Implement lshift, modulo, multiply, power, rshift of bool.

## Week 5: June 26 – 30

Implement floor_divide, true_divide of bool. Complete the inplace operations of bool.

## Week 6: July 3 – 7

Implement eq, ge, gt, le, lshift, lt, ne, rshift of range.

## Week 7: July 10 – 14

Implement add, and, floor_divide, or, power, subtract, true_divide and xor of range. 

## Week 8: July 17 – 21

Implement modulo, multiply of range. Now complete all it's inplace operations. 

## Week 9: July 24 – 28

Complete implementation of the remaining operations of complex datatype.

## Week 10: July 31 – Aug 4

Load the re module and have a basic regular expression library working. Write required tests to ensure it is not broken later.

## Week 11: Aug 7 – 11

Research extensively all subtle differences between re module in 2.4 and in 3.4.

## Week 12: Aug 14 – 18

Document and write tests for all differences that need to implemented.

**Comment by freakboy3742** [comment]
This is a good start. It's especially helpful that you've identified a pure-python implementation of the sre module; and the summary of historical conversations is also very useful.

My questions:
* Yes, there's only 2 methods left on complex. Have you investigated *why* they're the only two left?

* A pure python implementation of regex is one way to provide this functionality -the other would be a javascript implementation. Given that javascript has builtin regex functionality, can you elaborate on why you've chosen to go the "pure python" path rather than using builtin functionality?

* The re module you've identified is almost quite old - it hasn't been touched in over 4 years, and it references Python 2.4 as a baseline. What has changed in the interim? Is this going to affect anything?

Regarding the schedule itself; I get the impression you've decided what you want to do, then split it up over 12 weeks, rather than 8. There's also lots of time allocated for "research" - which is what this proposal phase is for. You should be getting to the GSoC period with a clear plan of what is to be done, and when it will be done - otherwise, your research might reveal that the task you've allocated 1 week will actually take 4.

**Comment by Sanjeev-S** [comment]
I really appreciate your feedback.

You mentioned that you get the impression that I decided what I wanted to do and then split it up. In a way that is correct. I decided that I wanted to work on some basic data types, summary about historical conversations(so that effort need not be replicated) and the re module. When I started thinking about how much time it would take, it came to about 11 weeks. And so I thought of expanding the datatypes part and hence decided to finish the complex data type too. Actually when I was looking at including one more data type, there was a comment in the tests for complex that said "These two work, but print floats not *quite* right due to JS Python differences". Since I'm re implementing the Python float function earlier, this felt like a logical data type to finish. I expect it wouldn't take too much effort. Then finish it's in-place operations too.

I've my reasoning on why I selected the python implementation over the JavaScript one. I'll think out loud from the beginning. Most of re module in CPython is written in C. There is a alternative regular expression module, to replace the new re which has all the features of re and more (https://pypi.python.org/pypi/regex/) but it is again implemented in C. Both can't really be used.
So now there are two plausible choices: using javascript's native regex or using the older pure python implementation(based on Python 2.4) and in both cases we want to get upto re Python 3.4 standards.
Python 3.4 re: https://docs.python.org/3.4/library/re.html
Python 2.4 re: https://docs.python.org/release/2.4.4/lib/module-re.html
JavaScript re: https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions.

If you use JavaScript native re, converting all of Python's extensions to its syntax would be hard work. Similar flags as in Python re are also missing.
Now let's look at the two Python re module. Even at first look, you can see re from 3.4 is an "extension" of re from 2.4.
2.4 Module contents: https://docs.python.org/release/2.4.4/lib/node115.html
3.4 Module contents: https://docs.python.org/3.4/library/re.html#module-contents
Most of the functions and constants are same. There are however changes, a few functions added. Optional flags arguments that can be passed in certain functions.

In my above proposal I hadn't planned on completing the Python 3.4 re module. I was proposing on getting a basic regex support working(from the 2.4 re module). Even if we are not completely in sync with the new re, I thought having regex support would be a good step.  And after that, by research I meant to compare line by line both the documentations and identify ALL of the functionalities missing and all of the subtle differences between 2.4 and 3.4 and document them with tests so that it could be implemented in future.(again here there's another advantage of using Python implementation from 2.4 instead of native regex from JavaScript, since the old Python documentation is in same format as the newer one and would be much easier to spot the differences and additions required).

**Comment by freakboy3742** [comment]
Unfortunately, this project was not accepted for GSoC 2017
