### ISSUE TITLE
GSOC: str, int, dict, sets, range and eval

### ISSUE THREAD

**Issue by memo330179** [pybee/batavia#478]
# Introduction

Completion of a project is important. In order for the product to be useful, it must provide a complete set of tools to work with. As it stands, Batavia has an extensive library of data structures and data types that make up the Python programming language. However, it also has many functions missing from those data types, as well as, some functions that are not behaving in the way they are expected to. In order for the project to come to fruition, these functions must be implemented. My work would be to implement some of the string functions that are still not working in the batavia project.

# Project Goals

## .format()

the tools I use the most when I am programming in Python are those found in the string object, and, of those, the string method I use the most is string formatting. In Python the recommended way to format string is using the built-in format function.

&quot;Hi, my name is {0} and I want to contribute to  {1}&quot;.format(&quot;Guillermo&quot;, &quot;Batavia&quot;)

Following the work of the implementation of string.\_\_mod\_\_ done by Jacob Stoebel, I want to add the new formatting style. 

## Other things

One thing that makes Python so cool is the fact that most of the time if you need to do something it has already been implemented. This is the case with sorting, treating lists as stacks, etc. It makes sense then that these functions that make Python so useful get added onto batavia. The team has done an excellent job so far and I would like to push it a bit further.

There are string functions that aren&#39;t implemented most of them are relatively simple. For example, isnumeric which would be a check to see if it is a number. (see more in timeline)

Most of the list functions have been implemented, but there are a few of them that have not such as pop or insert. These functions are important to be able to treat lists as stacks or queues.

(see more in timeline)

The dictionary module is also lacking some functions such as setdefault (see more in the timeline)

Set is also missing just a couple methods that make it cooler as well as alternate ways to call existing methods

It used to be that range was a list and so you could call list methods on it, but this changed and not it is a range class. However, the usefulness of it should be the same and collection methods were added to it so that you could do things such as use the in operator or access elements using an index. I would like to implement those as well.

# Implementation

## \.format() ##

The implementation of this would follow the implementation described in PEP 3101. Some of the requirements for this project are:

- Being able to distinguish markup from data:
  - In the code &quot;My name is {0}&quot;.format(&#39;Fred&#39;), &quot;My name is&quot; would be the data and would be passed directly, whereas {0} signifies text to be changed.
  - Braces should be able to be escaped by doubling them &quot;{{}}&quot; -&gt; {}
- A developer can use a name or a string to define what the markup needs to be replaced with.
  - &quot;My name is {0}&quot;.format(&#39;Fred&#39;) uses a number, but the same result can be obtained by using &quot;my name is {name}&quot;.format(name=&quot;Fred&quot;).
- There can be complex names that either user the &#39;.&#39; getattr or the &#39;[]&#39; getitem which will depend on the object that is passed through.
- It should be able to be formatted using format specifiers.
  -  EX: &quot;this is a binary number: {0:b}&quot;.format(2) -&gt; &quot;this is a binary number: 10&quot;
  - The format specifiers will follow the format [[fill]align][sign][#][0][minimumwidth][.precision][type]
  - The format identifiers are (taken from PEP 3101):
    - Align
      - &#39;&lt;&#39; - Forces the field to be left-aligned within the available space (This is the default.)
      - &#39;&gt;&#39; - Forces the field to be right-aligned within the available space.
      - &#39;=&#39; - Forces the padding to be placed after the sign (if any) but before the digits.  This is used for printing fields in the form &#39;+000000120&#39;. This alignment option is only valid for numeric types.
      - &#39;^&#39; - Forces the field to be centered within the available space.
    - Sign (only numericals)
      - &#39;+&#39;  - indicates that a sign should be used for both positive as well as negative numbers
      - &#39;-&#39;  - indicates that a sign should be used only for negative numbers (this is the default behavior)
      - &#39; &#39;- indicates that a leading space should be used on positive numbers
      - If the &#39;#&#39; character is present, integers use the &#39;alternate form&#39; for formatting.  This means that binary, octal, and hexadecimal output will be prefixed with &#39;0b&#39;, &#39;0o&#39;, and &#39;0x&#39;, respectively.
      - &#39;width&#39; is a decimal integer defining the minimum field width.  If not specified, then the field width will be determined by the content. If the width field is preceded by a zero (&#39;0&#39;) character, this enables zero-padding.  This is equivalent to an alignment type of &#39;=&#39; and a fill character of &#39;0&#39;.
      - The &#39;precision&#39; is a decimal number indicating how many digits should be displayed after the decimal point in a floating point conversion.  For non-numeric types the field indicates the maximum field size - in other words, how many characters will be used from the field content.  The precision is ignored for integer conversions.
    - Type
      - Integers
        -  &#39;b&#39; - Binary. Outputs the number in base 2.
        -  &#39;c&#39; - Character. Converts the integer to the corresponding Unicode character before printing.
        -  &#39;d&#39; - Decimal Integer. Outputs the number in base 10.
        - &#39;o&#39; - Octal format. Outputs the number in base 8.
        - &#39;x&#39; - Hex format. Outputs the number in base 16, using lower-case letters for the digits above 9.
        -  &#39;X&#39; - Hex format. Outputs the number in base 16, using upper-case letters for the digits above 9.
        - &#39;n&#39; - Number. This is the same as &#39;d&#39;, except that it uses the current locale setting to insert the appropriate number separator characters.
        - &#39;&#39; (None) - the same as &#39;d&#39;
      - Floats
        - &#39;e&#39; - Exponent notation. Prints the number in scientific notation using the letter &#39;e&#39; to indicate the exponent.
        - &#39;E&#39; - Exponent notation. Same as &#39;e&#39; except it converts the number to uppercase.
        - &#39;f&#39; - Fixed point. Displays the number as a fixed-point number.
        - &#39;F&#39; - Fixed point. Same as &#39;f&#39; except it converts the number  to uppercase.
        - &#39;g&#39; - General format. This prints the number as a fixed-point  number, unless the number is too large, in which case it switches to &#39;e&#39; exponent notation.
        -  &#39;G&#39; - General format. Same as &#39;g&#39; except switches to &#39;E&#39; if the number gets too large.
        - &#39;n&#39; - Number. This is the same as &#39;g&#39;, except that it uses the current locale setting to insert the appropriate number separator characters.
        - &#39;%&#39; - Percentage. Multiplies the number by 100 and displays in fixed (&#39;f&#39;) format, followed by a percent sign. &#39;&#39; (None) - similar to &#39;g&#39;, except that it prints at least one digit after the decimal point.
      - Object
        - Objects are able to define their own formatting using \_\_format\_\_
    - Conversion Flag
      - !r - convert the value to a string using repr()
      - !s - convert value to string using str()

# Timeline

At 12 weeks I would have 60 days to complete the project. The timeline for this project would be as follows:

- .format in batavia
  - Day 1: Study and understand the way in which cPython does the string formatting.
  - Day 2-3: Create the parser that will get the markup along with formatting options.
  - Day 4: Replace simple markups {0} or {name} appropriately
  - Day 5: Implement the ability of get attributes or get item using &quot;.&quot; or &quot;[]&quot;
  - Day 6-7: Add ability to get format identifiers to the parser
  - Day 8: implement string methods ljust, rjust  &lt;, &gt; and ^
  - Day 9: implement = +, -, &#39; &#39; implement &#39;width and precision&#39;
  - Day 10: implement b, d, o, none
  - Day 11: implement x and X, t, and n
  - Day 12: implement e, f, E and F
  - Day 13: implement g, G,n-float and % float
  - Day 14: implement object format override, r! And s!
  - Day 15-16: add ability for the parser to parametize nested {}
  - Day 17: implement global function, int, float, object format
  - Day 18: merge changes to main repository
- .format in VOC
  - Days 19-29: Ditto on days 2-18
- Finish String
  - Day 30: implement casefold, center, count, expandtabs
  - Day 31: Implement  find, index, isalnum, isalpha, isnumeric, isdigit,
  - Day 32: implement isprintable, isspace, and istitle
  - Day 33: Implement maketrans, partition,
  - Day 34: replace,  rfind, rindex, rjust, rpartition, Merge code
  - Day 35: splitlines, title, translate, upper, zfill
  - Day 36: Merge code
- Add to List
  - Day 37: Implement max, min, count, index
  - Day 39: Implement insert, pop, remove
- Add to dict
  - Day 40: Implement fromkeys, has\_key, setdefault
  - Day 41: Implement discard, pop and clear
  - Day 42: Fix values() (it is returning a list when it should be returning an object), Fix keys()
- Add to int and float
  - Day 43: Implement bit\_length, to\_bytes, as\_ratio\_integer
  - Day 44: Implement from\_bytes, hex, fromhex
- Sets
  - Day 44: fix len() of sets currently giving an error, implement clear function
  - Day 46: implement pop, discard
  - Day 47 Implement issubset, issuperset, union, Implement intersection, difference, Implements symmetric difference, intersection\_update, difference\_update,. These are already implemented, but they need to be able to be called using these function name.
- Range
  - Day 47 implement in operator, index
- Eval
  - Days 48-60
    - Implement code object
    - Implement parser for string
    - Implement code execution using globals and locals

# Success

Working string functions:

- format()
- isalnum()
- isnumeric()
- isdigit()
- isprintable()
- Isspace
- Istitle
- Swapcase

\_\_format\_\_ functions for

- Int
- Float
- object

Working Global format function

Implemented methods of various data types as described by the timeline

Being able to execute code objects using eval

# About Me

**Comment by memo330179** [comment]
I missed the GSOC window, but I would like to continue this on my own time.

**Comment by freakboy3742** [comment]
Unfortunately, this project was not selected for the 2017 GSoC. 

If you wish to continue on any parts of this project, feel free; however, it doesn't need to be associated with this GSoC planning ticket.
