### ISSUE TITLE
GSOC 2017: Implementation of ‘random and ‘re’. Complete implementation of float, bool and int

### ISSUE THREAD

**Issue by EGJ1996** [pybee/batavia#486]
# Implementation of ‘random and ‘re’. Complete the implementation of float, bool and int
### 02.04.2017
─
## About me:
I am Emiljano Gjiriti, a third year student majoring in computer science and mathematics at the American University in Bulgaria.. These days, I have tried to contribute to the project to get an idea of this initiative and this experience has further strengthened my positive opinion about the project and about the mentors who have been very willing to help a beginner like me get started. I contributed to the project by writing the methods for the power of complex numbers: https://github.com/pybee/batavia/pull/485 . I am also familiar with git and cricket-unittest, two technologies I consider very important while working with this project. If I get selected for the Google Summer of Code, this project would be my top priority during the summer and I am willing to put 40+ hours of work per week on it

## Overview
For the Google Summer of Code, I would like to work on Batavia, an implementation of the Python virtual machine written in Javascript. I plan on working on the re and random modules.  Generating random numbers is a commonly used functionality, often implemented as a standard library in most of the programming languages. For the random module, I would like to implement the following methods:
 
•	randrange
•	randint
•	choice (weighted and unweighted)
•	shuffle
•	sample
•	random
•	uniform
•	expovariate
•	gauss
•	lognormvariate
 
Python random module also has functionalities for generating random numbers according to: Triangular distribution, Beta distribution, Gamma distribution, Gaussian distribution, von Mises distribution, Paretto distribution, Weibull distribution. However, I will implement these methods only if I finish the implementation of the listed methods on time, because I don’t regard their implementation as crucial to the random module and I think that the normal, exponential and uniform distributions are mostly used. The only method that is currently implemented both in Javascript and in Python is the random method, used to generate random numbers between 0 and 1. The other methods have to be implemented from scratch. 
Regarding the re module, I plan to implement the following methods:
 
•	group
•	search
•	match
•	split
•	sub
•	fullmatch
•	findall
 
`search()`, `fullmatch()` and math() methods can be easily implemented using the match method of the JavaScript Regexp library. This method returns an object of the type` {matched substring, index:leftmost_index_where_the_pattern_was_found, input}`. In Python, we should return an object when all of these methods are called. In the match() method, in case the index is greater than 0, we should return the None object.  In the `fullmatch()` method, in case the length of the substring is less than the length of the string, we should return the none object. In case search, `match()` or` fullmatch()` are successful, we should return an object that contains information about the matched substring. So, in order to implement these methods, I should also create a new class, `_sre.SRE_Match`. The Javascript Regexp library also has two methods called split() and replace(), so the methods `split()` and `sub()` can be implemented using these two methods. The sub() method in Python as well as the `replace()` method in Javascript returns a string, so these two methods are compatible with one-another. The `split()` method in both languages return an array, so they are also compatible with one-another.  The `findall()` method can also be implemented using the match method of the JavaScript Regexp library. If we run the match method on a while loop until we get a null match and push the results in an array, we get the same functionality as the `findall()` method in Python. The group functionality can also be implemented in JavaScript using the same round bracket notation as in Python.

# Timeline

                                  # Part 1(Implementation of random module)
## Community Bonding: May 4 – 30
•	Involvement with mentors and colleagues on github and gitter
•	Research about the differences in regular expressions in Python and Javascript
•	Refresh my math knowledge on normal, uniform and exponential distributions and learn about the math behind the weighted choice() function

## Week 1: May 30 – June 5
•	Implement `randrange()`
•	Implement `randint() `(Implementation of `randint()` is just a call to `randrange()`)

## Week 2: June 7 – 12
•	Implement `choice()` and `shuffle()`
•	Implement `sample()`

## Week 3: June 14 – 18
•	Implement `choices()` method, which is a version of the above choice method but with weighted elements.
•	Implement `uniform()`, a method for generating random numbers according to uniform distribution.

## Week 4: June 20 – 28
•	Revise the math behind different distributions
•	Implement `lognormvariate(),` `expovariate(),` `gauss()`, methods for generating random numbers according to log-normal, exponential and Gaussian distribution respectively.

## Week 5: June 30– July 5
•	Revise the implementation of the random library
•	If no problems are encountered, I will implement the other distributions of random library i.e.: `gammavariate(),` `betavariate()` and `paretovariate()` 

                               # Part 2(Implementation of re module)
## Week 6: July 7 – 12
•	Start the implementation of the re module
•	Learn the theory about regular expressions
•	Learn the differences between regular expressions in Python and JavaScript

## Week 7: July 13 – 18
•	Create a `_sre.SRE_Match` class to return information about the matched pattern in order to emulate Python behavior for `search()` and `match()`
•	Implement the `search()` method based on the `match()` method of JavaScript's Regexp library.

## Week 8: July 19-23
•	Implement `match()` and `fullmatch()` based on the `match()` method of JavaScript's Regexp library.
•	Implement `split()` and `sub().` The implementation of these methods will be easy because they share the same behavior as their JavaScript counterparts.

## Week 9: July 25 – 30
•	Implement the `group()` method. This method will also be based on JavaScript's match method.
•	Revise the implementation of the re module and make sure that everything works properly.

                        # Part 3 ( Finish the implementation of bool, int and float)
## Week 10: Aug 1– Aug 8
•	Finish implementation of int
•	I anticipate that most of my time during this week will be devoted on the division of an integer with a complex number, on implementing the power of an integer with a complex exponent and on handling overflows in case of right shifts

## Week 11: Aug 9 – 15
•	Finish the implementation of the Boolean datatype
•	I anticipate that finishing the Boolean datatype will be an easy task because it is just a special case of int, with 0 replacing False and 1 replacing True

## Week 12: Aug 17 – 23
•	Finish the implementation of the float datatype
•	Fix the print function
•	I anticipate that most of my time during this week will be devoted to raising a float number to complex power and dividing a float number with a complex number.

## Week 13: Aug 25 – 29
•	Final checks on random module, re module and the three implemented datatypes
•	Submission of final work for evaluation

**Comment by freakboy3742** [comment]
Unfortunately, this project was not selected for the 2017 GSoC.
