### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by pranair** [pybee/batavia#515]
The link for the project [internals](http://batavia.readthedocs.io/en/latest/internals/index.html) is broken.

**Comment by li3n3** [comment]
Where is this linked from?

**Comment by pranair** [comment]
@li3n3 [README.rst](https://github.com/pybee/batavia/edit/master/README.rst) line number 125

**Comment by morrme** [comment]
doesn't seem to be a corresponding article anywhere in the current docs
