### ISSUE TITLE
str() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by FeralBytes** [pybee/batavia#53]
Essentially I just tried to do the tutorial and putting 
`print('Hello World')`
into the text area and clicking run immediately resulted in a trace-back. Is this due to django running as python 2. Because the Shebang says python not python3.

By the way this is an awesome concept and so small and light weight! I am going to start testing if I can do AJAX using it; has this already been tested; are there some examples?

**Comment by FeralBytes** [comment]
[I made a pull request here](https://github.com/FeralBytes/batavia/pull/1)
Please review it and let me know which method you would like to use to detect python3 and I will make a proper pull request against your project.

**Comment by FeralBytes** [comment]
OK new pull request created using the preferred method; sorry for the multiple commits; I can pull it back and make a single commit if you would prefer? I did not test it until after the first commit.

**Comment by freakboy3742** [comment]
Github lets me collapse multiple-commit pull requests into a single commit with a single button press, so don't worry about collapsing. There are a couple of comments against the patch; if you can address those, we can merge!

**Comment by FeralBytes** [comment]
Done.
