### ISSUE TITLE
test_add_none does not exist.

### ISSUE THREAD

**Issue by betojulio** [pybee/batavia#57]
test_add_none is in the not_implemented list in file test_str.py.

if I run "python setup.py test -s tests.datatypes.test_str.BinaryStrOperationTests.test_add_none" to work on this test case I get 'type object 'BinaryStrOperationTests' has no attribute 'test_add_none''

**Comment by freakboy3742** [comment]
Thanks for the report! Looks like an oversight when I copied the test code over from VOC. I'll commit a fix shortly.
