### ISSUE TITLE
Error while running $ python compile_stdlib.py

### ISSUE THREAD

**Issue by jarnugirdhar** [pybee/batavia#575]
While following http://batavia.readthedocs.io/en/latest/intro/tutorial-0.html this tutorial, in Troubleshooting Tips it is mentioned to run $ python compile_stdlib.py command in order to remove error which occur during $ npm run build. But the following "Syntax error" occurred when I ran $python compile_stdlib.py

Although after this I ran $ npm run build it ran successfully, but still why the error? 

![error](https://user-images.githubusercontent.com/28496978/27269263-2676d9c8-54d3-11e7-9c82-3021284cfca0.png)

**Comment by glasnt** [comment]
Hi @jarnugirdhar. Can you please confirm what version of python you are using by running `python -V`

It looks like you might not be using Python 3. As per the tutorial, Batavia requires at least Python 3.4

**Comment by jarnugirdhar** [comment]
`python -V` shows python 2.7.2, but I have installed latest python3.x which I can access using `python3` Do I need to do some alterations in system? (I am running Ubuntu 16.04 LTS)

**Comment by glasnt** [comment]
In that case, run `python3 compile_stdlib.py`, and substitute `python3` where required.

**Comment by jarnugirdhar** [comment]
Thanks, resolved.
