### ISSUE TITLE
Can i remove passed test?

### ISSUE THREAD

**Issue by sebassdc** [pybee/batavia#669]
Im running `test.datatypes.test_str.StrTests` and all pass, can i delete the test that pass correctly?

**Comment by freakboy3742** [comment]
@sebassdc No - you don't ever *delete* tests - the point of tests is to keep running them after every change to make sure that behavior doesn't change unexpectedly as a result of some future change.

The only things you *might* delete are entries in the "not_implemented" lists, or @expectedFailure markers. However, you should only be deleting these in response to implementing some new functionality that causes those tests that pass.

Does that make sense?

**Comment by sebassdc** [comment]
Thanks, it was a pretty little big confusion. 😅
