### ISSUE TITLE
Behavior

### ISSUE THREAD

**Issue by head61771** [pybee/batavia#677]
## Steps to reproduce

1.

2.

3.

## Your Environment

* Python Version (list the specific version number)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] OSX
  - [ ] Linux
  - [ ] Windows
  - [ ] Ubuntu

**Comment by glasnt** [comment]
Hi! It looks like you submitted an empty issue. I'll close this for now; if you want to come back and edit it, please feel free
