### ISSUE TITLE
joining

### ISSUE THREAD

**Issue by likithb12** [pybee/batavia#680]
## Steps to reproduce

1.

2.

3.

## Your Environment

* Python Version (list the specific version number)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] OSX
  - [ ] Linux
  - [ ] Windows
  - [ ] Ubuntu

**Comment by glasnt** [comment]
Hi! It looks like you created an empty issue. I'm going to close this. I hope to see you contribute to batavia soon ✨
