### ISSUE TITLE
docs/index.rst in toctree ‘project/index’

### ISSUE THREAD

**Issue by persona5173** [pybee/batavia#686]
An error occurred in 'make html' while building sphinx to contribute docs.

I looked at 'index.rst' to find out why.
In 'index.rst', 'project'directory does not exist, but there was code that references' project / index'.

How do I fix this?

/Users/jinhyeok/Desktop/OpenSource_CNU/pybee/batavia/docs/index.rst:98:toctree contains reference to nonexisting document 'project/index'
make: *** [html] Error 1
![image](https://user-images.githubusercontent.com/18658656/32728651-793e280e-c8c4-11e7-806b-f5ba6d1a64c4.png)

![image](https://user-images.githubusercontent.com/18658656/32728664-84f16ea4-c8c4-11e7-8910-5fc7e909efa7.png)

'index.rst' has 'project/index'.

![image](https://user-images.githubusercontent.com/18658656/32728687-9e2152ea-c8c4-11e7-9db9-d47249557015.png)

But 'docs'directory doesn't have 'project'directory

## Your Environment

* Python Version (list the specific version number)
python 3.5.0

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [✓] OSX\

**Comment by freakboy3742** [comment]
Looks like a stale reference - there would have been a project/index.rst until recently; but it looks like I didn't run a full rebuild before pushing the PR. You should be able to just delete the line (and submit a PR of that!)

**Comment by persona5173** [comment]
Thank you!! :)
I solved the issue and submit a PR!
