### ISSUE TITLE
CPython 3.6+ is switching to a 16-bit wordcode format

### ISSUE THREAD

**Issue by freakboy3742** [pybee/batavia#71]
Via @ncoghlan, reporting pybee/voc#132: 

This is an early heads up that CPython will be switching to a 16-bit wordcode format as of 3.6a2: http://bugs.python.org/issue26647

The change itself is in https://hg.python.org/cpython/rev/3a57eafd8401

In theory this should be a transparent change for any project that interacts with compiled code solely through the `dis` module, but since VoC transpiles CPython bytecode I figured you may want to take a closer look at the implications.

**Comment by freakboy3742** [comment]
See also #26, for the changes affecting CPython 3.5.

**Comment by dibyadas** [comment]
Now that VOC uses AST to do it, do you think this is issue is relevant any more?

**Comment by cjrh** [comment]
I've begun implementation of 16-bit wordcode in PR #536. The changes are wound up in also trying to get dicts to work for 3.6.1. Unfortunately, both the 16-bit wordcode change as well as the _new_ opcode changes (like the new dict support) have to be done at the same time.

**Comment by cjrh** [comment]
I've begun the process of using the 16-bit wordcode format in PR #536.

**Comment by Zac-HD** [comment]
Closed by #621?

**Comment by freakboy3742** [comment]
@Zac-HD Indeed it is. Thanks!
