### ISSUE TITLE
Issue with __local__ on sample.py

### ISSUE THREAD

**Issue by glasnt** [pybee/batavia#8]
I tried to run the sample.py via the testserver harness, and got some issues, which I think I resolved in #7 .

However, now I'm seeing the python error `NameError: local variable '__locals__' referenced before assignmentnull`  in the testserver output.

It appears to be coming from the `Point` class, because if I remove the `Point` class code from sample.py code, it runs ok.

**Comment by freakboy3742** [comment]
I'm definitely not seeing this; Can you provide details about the test environment? In particular:
* Django version
* Python version (including value of sys.maxsize)
* Operating system + version

**Comment by glasnt** [comment]
```
$ uname -a
Linux  3.13.0-62-generic #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ django-admin version
1.8.4
$ python -V
Python 3.3.3
```

**Comment by freakboy3742** [comment]
I take it this is under Chrome on Ubuntu? 

Also - I also note that you're using Python 3.3 on the server; I don't *think* that will be a problem - I'm not aware of any incompatibilities in the bytecode between 3.3 and 3.4, but it's noteworthy. Is that the stock Python3 from apt-get? And if so - which Ubuntu release are you using?

**Comment by glasnt** [comment]
Ubuntu 14.04 LTS
Python3 is latest from apt-get

**Comment by glasnt** [comment]
Yup, this totally works using python 3.4.1 as opposed to python 3.3.3

Tested to work on both Firefox and Chromium.


Interestingly enough, running the testserver from commit b69b2b7 works as is for me now, using this new python version. So the changes in #7 might be superfluous, but meh.

Closing issue.
